apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: task-app
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - app-deployment.yaml
  - app-service.yaml
  - hpa.yaml
  - configmap.yaml
  - secret-placeholders.yaml
  - ingress.yaml
