apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: task-app-secret
  namespace: task-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameterstore
    kind: ClusterSecretStore
  target:
    name: task-app-secret
    creationPolicy: Owner
  data:
    - secretKey: database_url
      remoteRef:
        key: task-app/database_url
    - secretKey: redis_url
      remoteRef:
        key: task-app/redis_url
