apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: task-app
resources:
  - ../../base
images:
  - name: 188362558545.dkr.ecr.us-east-1.amazonaws.com/task-app
    newTag: dev
patchesStrategicMerge:
  - app-configmap-patch.yaml
