apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: task-app
resources:
  - ../../k8s/base
images:
  - name: <aws_account_id>.dkr.ecr.<region>.amazonaws.com/task-app
    newTag: dev
configMapGenerator:
  - name: task-app-config
    behavior: merge
    literals:
      - app_env=dev
