apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: task-app
resources:
  - ../../base
images:
  - name: <aws_account_id>.dkr.ecr.<region>.amazonaws.com/task-app
    newTag: dev
patchesStrategicMerge:
  - app-configmap-patch.yaml
