- op: replace
  path: /apiVersion
  value: v1
- op: replace
  path: /kind
  value: Secret
- op: remove
  path: /spec
- op: add
  path: /type
  value: Opaque
- op: add
  path: /stringData
  value:
    database_url: postgres://db_admin_user:db_password@postgres:5432/task_database?sslmode=disable
    redis_url: redis://:redis_password@redis:6379/0
