name: CD - App

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - app/**
      - k8s/**
      - .github/workflows/cd-app.yaml

permissions:
  id-token: write
  contents: write
  
env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
  AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Extract AWS account ID
        id: aws-info
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          ACCOUNT_ID="${REGISTRY%%.*}"
          echo "account_id=$ACCOUNT_ID" >> "$GITHUB_OUTPUT"

      - name: Build and push image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd app
          docker build -t $REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG .
          docker push $REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Update manifest image tag
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
        run: |
          OLD_IMAGE="<aws_account_id>.dkr.ecr.<region>.amazonaws.com/task-app:${IMAGE_TAG}"
          NEW_IMAGE="${REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}"

          sed -i "s#${OLD_IMAGE}#${NEW_IMAGE}#" k8s/base/app-deployment.yaml

      - name: Replace AWS placeholders in manifests
        env:
          AWS_ACCOUNT_ID: ${{ steps.aws-info.outputs.account_id }}
          AWS_REGION: ${{ env.AWS_REGION }}
        run: |
          sed -i "s#<account_id>#${AWS_ACCOUNT_ID}#g" k8s/base/serviceaccount.yaml logging/fluent-bit/fluent-bit-config.yaml
          sed -i "s#<aws_account_id>#${AWS_ACCOUNT_ID}#g; s#<region>#${AWS_REGION}#g" k8s/overlays/dev/kustomization.yaml

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add k8s/base/app-deployment.yaml k8s/base/serviceaccount.yaml k8s/overlays/dev/kustomization.yaml logging/fluent-bit/fluent-bit-config.yaml
          git commit -m "chore: update image tag to ${GITHUB_SHA}" || echo "No changes to commit"
          git push
